# azure-pipelines-app.yaml

trigger:
  branches:
    include:
      - main

stages:
  - stage: DeployApp
    displayName: "Deploy Application Code via Ansible"
    jobs:
      - job: App_Deployment
        displayName: "Run Ansible Playbook to Deploy App"
        pool:
          name: "SelfHostedPoolAdrina"

        steps:
          - script: |
              sudo apt update
              sudo apt install -y ansible sshpass
            displayName: "Install Ansible & SSH dependencies"

          - task: DownloadSecureFile@1
            name: download_ssh_key
            inputs:
              secureFile: "br_id_ed"

          - script: |
              mkdir -p ~/.ssh
              cp $(download_ssh_key.secureFilePath) ~/.ssh/br_id_ed
              chmod 600 ~/.ssh/br_id_ed
              echo "StrictHostKeyChecking no" > ~/.ssh/config
            displayName: "Setup SSH Private Key"

          - script: |
              cd ansible
              ansible-playbook -i inventory.ini site.yml --ssh-extra-args "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
            displayName: "Run Ansible Playbook"
            env:
              ANSIBLE_HOST_KEY_CHECKING: "False"
